name: QC Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    name: QC Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: corepack enable
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: "22.20.0"
          package-manager-cache: false

      - name: Install
        run: |
          yarn config set enableImmutableInstalls false
          yarn install

      - name: ESLint checks
        run: npm run check-lint

      - name: Prettier checks
        run: npm run check-format

      - name: TSC checks
        run: npm run check-tsc

  tests:
    name: Tests Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v5

      - run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Install system dependencies for Electron
        run: npx playwright install-deps

      - name: Install
        run: |
          yarn config set enableImmutableInstalls false
          yarn install

      - name: Run tests
        run: xvfb-run --auto-servernum -- npx mocha
